name: Build and deploy U2NET salient object detection flask app to server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#     - uses: actions/checkout@v2

# #     - name: Authenticate with Azure
# #       uses: azure/login@v1
# #       with:
# #         creds: ${{secrets.AZURE_CREDENTIALS}}

# #     - name: set auto-install of extensions
# #       run: az config set extension.use_dynamic_install=yes_without_prompt

# #     - name: attach workspace
# #       run: az ml folder attach -w "clipcraft-studio" -g "sunkwenga-rg"

# #     - name: retrieve the model
# #       run: az ml model download -t "." --model-id "U2Net:1"
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: build flask-app container
#       uses: docker/build-push-action@v2
#       with:
#         context: ./
#         platforms: linux/amd64,linux/arm64
#         file: ./Dockerfile
#         push: false
#         tags: perplexedyawdie/clipcraft-u2net:latest
        
#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v1
#       with:
#         registry: ghcr.io
#         username: ${{ github.repository_owner }}
#         password: ${{ secrets.GH_REGISTRY }}
    
#     - name: build flask-app and push to registry
#       uses: docker/build-push-action@v2
#       with:
#         context: ./
#         provenance: false
#         tags: ghcr.io/perplexedyawdie/clipcraft-u2net:latest
#         push: true
        
  deploy:
#     needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_REGISTRY }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: SSH into server and deploy container
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REGISTRY }}
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            if [ $(docker ps -a -q -f name=clipcraft-u2net) ]; then
              docker stop clipcraft-u2net && \
              docker rm clipcraft-u2net
            fi
            rm -rf clipcraft-u2net-flask && \
            git clone https://github.com/perplexedyawdie/clipcraft-u2net-flask.git && \
            cd clipcraft-u2net-flask && \
            docker --network host build -t clipcraft-u2net-flask:latest . && \
            docker run -d -p 8003:5000 --name clipcraft-u2net clipcraft-u2net-flask:latest "
